export const categories: string[] = [
    "Technology",
    "Web Development",
    "Mobile App Development",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Cybersecurity",
    "Blockchain",
    "DevOps",
    "Business",
    "Entrepreneurship",
    "Business Strategy",
    "Marketing",
    "Finance and Accounting",
    "Project Management",
    "Leadership",
    "Human Resources",
    "Design",
    "Graphic Design",
    "Web Design",
    "UX/UI Design",
    "3D Animation",
    "Game Design",
    "Personal Development",
    "Personal Finance",
    "Time Management",
    "Goal Setting",
    "Mindfulness and Meditation",
    "Communication Skills",
    "Language",
    "English Language",
    "Spanish Language",
    "French Language",
    "German Language",
    "Chinese Language",
    "Health and Fitness",
    "Fitness Training",
    "Nutrition",
    "Yoga",
    "Mental Health and Well-being",
    "Arts and Music",
    "Drawing and Painting",
    "Music Production",
    "Guitar",
    "Piano",
    "Science",
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Academic Subjects",
    "Mathematics",
    "History",
    "Literature",
    "Social Sciences",
    "Test Preparation",
    "SAT/ACT Prep",
    "GRE/GMAT Prep",
    "Professional Certification Exams",
    "Hobbies and Interests",
    "Cooking",
    "Gardening",
    "Travel",
    "DIY and Crafts",
    "Photography",
    "Programming and Software Tools",
    "Python",
    "Java",
    "JavaScript",
    "React",
    "Angular",
    "Docker",
    "Kubernetes",
    "Career Development",
    "Resume Writing",
    "Job Interview Skills",
    "Career Coaching",
    "Specialized Industries",
    "Real Estate",
    "Healthcare",
    "Hospitality and Tourism",
    "Retail",
    "Language Learning",
    "Language Learning for Travel",
    "Conversational Language Skills"
] 