export const currencies: string[] =[
    '$',    // United States Dollar (USD)
    '€',    // Euro (EUR)
    '£',    // British Pound Sterling (GBP)
    'Fr.',  // Swiss Franc (CHF)
    'C$',   // Canadian Dollar (CAD)
    'A$',   // Australian Dollar (AUD)
    '¥',    // Chinese Yuan (CNY)
    '₹',    // Indian Rupee (INR)
    'R$',   // Brazilian Real (BRL)
    'R',    // South African Rand (ZAR)
    '₽',    // Russian Ruble (RUB)
    '₺',    // Turkish Lira (TRY)
    'kr',   // Swedish Krona (SEK)
    'zł',   // Polish Złoty (PLN)
    'Mex$', // Mexican Peso (MXN)
    '₱',    // Philippine Peso (PHP)
    'S$',   // Singapore Dollar (SGD)
    '฿',    // Thai Baht (THB)
    '₨',    // Pakistani Rupee (PKR)
]